### ISSUE TITLE
CHANGE: txt-ben tárolás

### ISSUE THREAD

**Issue by ExAtom** [14A-A-Lyedlik-Devs/futar-nodejs#34]
A feladat az volt, hogy a txt forrás txt-ben is maradjon, nem kellett json-ben tárolni.

**Comment by Rettend** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Rettend** [comment]
oké ezt megcsináljuk órán holnap, **de meg kell menteni a json fájlt a backendnek!!**
