### ISSUE TITLE
[BUG] Nits tanácsok

### ISSUE THREAD

**Issue by ExAtom** [14A-A-Lyedlik-Devs/futar-nodejs#37]
- [x] Saláta Fájlbaírás függvényt ki kell bontani
- [x] plusz forrásfájlra tesztelés (lehetőleg olyat, amiben lesznek hiányosságok - tehát egyes feladatokra nem talál semmit - hogy 100%-os lehessenek a tesztek)
- [x] Content.ts-ben az üres zárójeleket el kell hagyni
- [x] Az egyik feladat, ahol join-nal van összefűzve a contentben, azt bele kellene tenni a függvénybe és a joinolt stringet visszeküldeni

**Comment by Rettend** [comment]
A tesztek neveibe írom hogy hányadik feladathoz tartoznak + így már sorba lehet rendezni őket
